# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Go to cd Betsson.OnlineWallets.Web
      run: cd src/Betsson.OnlineWallets.Web
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run application
      run: dotnet run
    - name: Go to test project
      run: cd ./Betsson.OnlineWallets.Api.Tests
    - name: Running API testing project
      run: dotnet test
